# Generated by Django 4.1.1 on 2022-11-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=255)),
                ('categoryphoto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Intolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intolerancename', models.CharField(max_length=255)),
                ('intolerancephoto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealname', models.CharField(max_length=255)),
                ('mealdesc', models.TextField()),
                ('price', models.FloatField()),
                ('mealphoto', models.CharField(max_length=255, null=True)),
                ('discount', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('userphoto', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserMealCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.category')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.meal')),
            ],
        ),
        migrations.CreateModel(
            name='IntoleranceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.category')),
                ('intolerance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.intolerance')),
            ],
        ),
    ]
