# Generated by Django 4.1.1 on 2022-11-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmtapp', '0003_questionintolerance_questioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgname', models.CharField(max_length=255)),
                ('cgphoto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wmtapp.categorygroup')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.question')),
            ],
        ),
        migrations.RemoveField(
            model_name='intolerancecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='intolerancecategory',
            name='intolerance',
        ),
        migrations.RemoveField(
            model_name='questionintolerance',
            name='intolerance',
        ),
        migrations.RemoveField(
            model_name='questionintolerance',
            name='question',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryname',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryphoto',
            new_name='cphoto',
        ),
        migrations.RenameField(
            model_name='mealcategory',
            old_name='category',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='questioncategory',
            old_name='category',
            new_name='c',
        ),
        migrations.DeleteModel(
            name='Intolerance',
        ),
        migrations.DeleteModel(
            name='IntoleranceCategory',
        ),
        migrations.DeleteModel(
            name='QuestionIntolerance',
        ),
        migrations.AddField(
            model_name='categorygroupcategory',
            name='c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.category'),
        ),
        migrations.AddField(
            model_name='categorygroupcategory',
            name='cg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.categorygroup'),
        ),
    ]
