# Generated by Django 4.1.1 on 2022-11-10 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wmtapp', '0005_question_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.meal')),
            ],
        ),
        migrations.CreateModel(
            name='UserBatchCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserBatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wmtapp.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='usermealhistory',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='usermealhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserMealCart',
        ),
        migrations.DeleteModel(
            name='UserMealHistory',
        ),
    ]
