# Generated by Django 4.1.1 on 2022-11-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmtapp', '0006_batch_userbatchcart_userbatchhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbatchcart',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userbatchhistory',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
