# Generated by Django 4.1.1 on 2022-11-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmtapp', '0007_userbatchcart_date_userbatchhistory_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbatchcart',
            name='date',
        ),
    ]
