# Generated by Django 4.1.1 on 2022-11-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmtapp', '0008_remove_userbatchcart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userphoto',
            field=models.TextField(null=True),
        ),
    ]
