# Generated by Django 4.1.1 on 2022-11-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmtapp', '0009_alter_user_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userphoto',
            field=models.TextField(default='https://cdn-icons-png.flaticon.com/512/1946/1946429.png', null=True),
        ),
    ]
